name: 'Deploy ChangeDetection.io to Lightsail'

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_VAR_whitelist_ips: ${{ secrets.WHITELIST_IPS }}
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
          terraform_version: 1.10.5
      
    - name: Terraform Init
      working-directory: ./terraform/dev
      run: terraform -chdir=terraform init
        
    - name: Terraform Validate
      working-directory: ./terraform/dev
      run: terraform -chdir=terraform validate

    - name: Terraform Plan
      working-directory: ./terraform/dev    
      run: terraform -chdir=terraform plan -input=false
      
    - name: Terraform Apply
      working-directory: ./terraform/dev
      if: github.ref == 'refs/heads/main'
      run: terraform -chdir=terraform apply -auto-approve -input=false